ArmaForces/Mods

.vscode/settings.json
=> Change automatic function headers to ACE standard

addons/friendly_tracker/$PBOPREFIX$, addons/friendly_tracker/CfgEventHandlers.hpp, addons/friendly_tracker/README.md, addons/friendly_tracker/XEH_PREP.hpp, addons/friendly_tracker/XEH_postInit.sqf, addons/friendly_tracker/XEH_preInit.sqf, addons/friendly_tracker/XEH_preStart.sqf, addons/friendly_tracker/config.cpp, addons/friendly_tracker/functions/fnc_createGroupMarker.sqf, addons/friendly_tracker/functions/fnc_createPlayerMarker.sqf, addons/friendly_tracker/functions/fnc_createVehicleMarker.sqf, addons/friendly_tracker/functions/fnc_getGroupMarkerType.sqf, addons/friendly_tracker/functions/fnc_getVehicleMarkerType.sqf, addons/friendly_tracker/functions/fnc_hasTracker.sqf, addons/friendly_tracker/functions/fnc_init.sqf, addons/friendly_tracker/functions/fnc_loop.sqf, addons/friendly_tracker/functions/fnc_stop.sqf, addons/friendly_tracker/functions/script_component.hpp, addons/friendly_tracker/initSettings.sqf, addons/friendly_tracker/script_component.hpp, addons/friendly_tracker/stringtable.xml
**This PR will:**
- Add BFT module
**To do:**
=> Add friendly_tracker

.gitattributes
=> Categorise hpp and cpp files as SQF in GitHub

addons/common/$PBOPREFIX$, addons/common/CfgEventHandlers.hpp, addons/common/XEH_postInit.sqf, addons/common/XEH_preInit.sqf, addons/common/XEH_preStart.sqf, addons/common/config.cpp, addons/common/functions/script_component.hpp, addons/common/script_component.hpp
=> Add common component

addons/back_to_game/$PBOPREFIX$, addons/back_to_game/CfgEventHandlers.hpp, addons/back_to_game/README.md, addons/back_to_game/XEH_PREP.hpp, addons/back_to_game/XEH_postInit.sqf, addons/back_to_game/XEH_preInit.sqf, addons/back_to_game/XEH_preStart.sqf, addons/back_to_game/config.cpp, addons/back_to_game/functions/fnc_deletePlayerData.sqf, addons/back_to_game/functions/fnc_dialogConfirm.sqf, addons/back_to_game/functions/fnc_dialogReject.sqf, addons/back_to_game/functions/fnc_getPlayerData.sqf, addons/back_to_game/functions/fnc_handleConnected.sqf, addons/back_to_game/functions/fnc_handleTeleport.sqf, addons/back_to_game/functions/fnc_hasDisconnected.sqf, addons/back_to_game/functions/fnc_savePlayerData.sqf, addons/back_to_game/functions/fnc_teleportPlayer.sqf, addons/back_to_game/functions/script_component.hpp, addons/back_to_game/initSettings.sqf, addons/back_to_game/script_component.hpp, addons/back_to_game/stringtable.xml, addons/back_to_game/teleportDialog.hpp
Refactored from preset crashTeleport, originaly created as mission script by Madin.
- Teleport back after crash/disconnect
- Restore loadout
=> Add back_to_game

.gitattributes
- Update linguist settings
- set `include/` dir as vendored (do not count in statistics)
- `*.inc` files as SQF
=> Update linguist settings

addons/friendly_tracker/README.md, addons/friendly_tracker/functions/fnc_createPlayerMarker.sqf
- Add support for Diwako DUI buddy (pink color)
=> Add support for Diwako DUI buddy

addons/slingload/$PBOPREFIX$, addons/slingload/CfgEventHandlers.hpp, addons/slingload/README.md, addons/slingload/XEH_postInitServer.sqf, addons/slingload/config.cpp, addons/slingload/script_component.hpp
- Improve performance of slingloading by making slingloaded cargo local to slingloading helicopter
Based on: https://github.com/Theseus-Aegis/Mods/tree/master/addons/slingload
=> Add slingloading component

addons/common/XEH_PREP.hpp, addons/common/config.cpp, addons/common/functions/fnc_modal.sqf, addons/common/functions/fnc_onModalClose.sqf, addons/common/functions/fnc_onModalOpen.sqf, addons/common/script_component.hpp, addons/common/ui/RscModal.hpp, addons/common/ui/script_component.hpp
=> Add modal dialog to common component

addons/difficulty/$PBOPREFIX$, addons/difficulty/CfgAILevelPresets.hpp, addons/difficulty/CfgDifficultyPresets.hpp, addons/difficulty/config.cpp, addons/difficulty/script_component.hpp, addons/difficulty/stringtable.xml
- Component with our customized difficulty settings
- "ArmaForces" difficulty set as default
=> Add Difficulty component

addons/main_menu/$PBOPREFIX$, addons/main_menu/CfgEventHandlers.hpp, addons/main_menu/CfgMainMenuSpotlight.hpp, addons/main_menu/XEH_PREP.hpp, addons/main_menu/XEH_postInit.sqf, addons/main_menu/XEH_preInit.sqf, addons/main_menu/XEH_preStart.sqf, addons/main_menu/config.cpp, addons/main_menu/functions/fnc_join.sqf, addons/main_menu/functions/script_component.hpp, addons/main_menu/script_component.hpp, addons/main_menu/stringtable.xml
- title
- Port of join server spotlight tile from legacy addons
Unfortunately the "join" function is still ugly but it's hard to do it better, if world is not loaded on main menu we have no CBA systems available.
=> Add main_menu component

hemtt.toml
=> Add Steam Workshop Id to hemtt.toml

addons/common/XEH_preInit.sqf, addons/main/script_macros.hpp, addons/safestart/XEH_preInit.sqf
- title
- check for `aceSafemode` in common and use that in safestart
=> Add IS_MOD_LOADED macro

addons/friendly_tracker/initSettings.sqf
=> Fix typo in `showGroups_Disabled` string

addons/safestart/config.cpp, addons/safestart/initSettings.sqf, addons/safestart/stringtable.xml
- Add missing `Safestart` settings translations
- Fix Safestart settings not appearing
=> Safestart translations and fixes

AUTHORS.txt
=> Alphabetize AUTHORS.txt

.github/labels.json, .github/workflows/labels.yml
- title
- to be used alongside [release drafter](https://github.com/marketplace/actions/release-drafter)
=> Define repository labels in json

addons/main_menu/script_component.hpp
=> Fix build on Linux

addons/main/script_version.hpp
=> Bump version for release 1.0.2

.github/workflows/release.yml
=> Add link to changelog to Steam change notes

addons/main/script_version.hpp
=> Bump version for release 1.0.3

addons/common/XEH_preInit.sqf, addons/fries/$PBOPREFIX$, addons/fries/CfgEventHandlers.hpp, addons/fries/README.md, addons/fries/XEH_postInit.sqf, addons/fries/XEH_preInit.sqf, addons/fries/config.cpp, addons/fries/initSettings.sqf, addons/fries/script_component.hpp, addons/fries/stringtable.xml
- Add FRIES component which auto adds FRIES to supported helicopters if ACE Fastroping is loaded
=> Add FIRES component

addons/respawn/README.md, addons/spectator/README.md, addons/spectator/config.cpp
- Add mission `afm_common` dependency to spectator
- Add spectator readme
- Add respawn readme
=> Spectator respawn fixes

addons/main/script_version.hpp
=> Bump version for release 1.0.4

addons/common/XEH_preInit.sqf, addons/fatigue/$PBOPREFIX$, addons/fatigue/CfgEventHandlers.hpp, addons/fatigue/README.md, addons/fatigue/XEH_PREP.hpp, addons/fatigue/XEH_postInit.sqf, addons/fatigue/XEH_preInit.sqf, addons/fatigue/XEH_preStart.sqf, addons/fatigue/config.cpp, addons/fatigue/functions/fnc_toggleHighJogFactor.sqf, addons/fatigue/functions/script_component.hpp, addons/fatigue/initSettings.sqf, addons/fatigue/script_component.hpp, addons/fatigue/stringtable.xml
- Add fatigue component
- title
=> Add custom high jog coefficient for ACE Advanced Fatigue

addons/spectator/CfgEventHandlers.hpp, addons/spectator/XEH_PREP.hpp, addons/spectator/functions/fnc_onDisplayLoad.sqf, addons/spectator/script_component.hpp
- title
<details>
<summary>Images</summary>
</details>
=> Move game time in spectator to right if respawn counter is enabled

addons/curator/CfgEden.hpp, addons/curator/XEH_postInit.sqf
=> Fix Zeus not added properly from Eden attribute

.vscode/launch.json
=> Add launch.json configuration for Arma Debug Engine

addons/common/XEH_preInit.sqf, addons/tagging/$PBOPREFIX$, addons/tagging/CfgEventHandlers.hpp, addons/tagging/README.md, addons/tagging/XEH_postInit.sqf, addons/tagging/XEH_preInit.sqf, addons/tagging/config.cpp, addons/tagging/initSettings.sqf, addons/tagging/script_component.hpp, addons/tagging/stringtable.xml
- title
- markers are created in _side_ channel, but due to current flaw in implementation of #49 visible to everyone
<details>
<summary>Video</summary>
https://streamable.com/274wa
</details>
=> Add markers on map when using ACE Tagging on buildings

addons/curator/XEH_postInit.sqf, addons/curator/XEH_preInit.sqf
- title
Do we want to have some settings for that?
=> Auto add objects to Zeus

addons/ai_disembark/$PBOPREFIX$, addons/ai_disembark/CfgEventHandlers.hpp, addons/ai_disembark/README.md, addons/ai_disembark/XEH_PREP.hpp, addons/ai_disembark/XEH_preInit.sqf, addons/ai_disembark/XEH_preStart.sqf, addons/ai_disembark/config.cpp, addons/ai_disembark/functions/fnc_onDisembark.sqf, addons/ai_disembark/functions/script_component.hpp, addons/ai_disembark/initSettings.sqf, addons/ai_disembark/script_component.hpp, addons/ai_disembark/stringtable.xml
=> Play weapon reload animation on AI disembark

addons/respawn/CfgRespawnTemplates.hpp, addons/respawn/functions/fnc_adjustTime.sqf, addons/respawn/functions/fnc_adjustTimeLocal.sqf, addons/respawn/functions/fnc_disable.sqf, addons/respawn/functions/fnc_enable.sqf, addons/respawn/functions/fnc_onPlayerKilled.sqf, addons/respawn/functions/fnc_onPlayerRespawn.sqf
=> Run respawn functions in unscheduled

addons/curator/XEH_postInit.sqf
=> Fix curator unassignment

.github/workflows/arma.yml, addons/killtracker/functions/fnc_dumpStats.sqf, addons/safestart/functions/fnc_lowerWeapon.sqf, addons/spectator/functions/fnc_canSpectate.sqf, tools/return_checker.py
- title
Based on https://github.com/zen-mod/ZEN/pull/318
=> Add return type validator for SQF files 

addons/main/script_version.hpp
=> Bump version for release 1.1.0

addons/common/functions/fnc_isUnconscious.sqf, addons/insurgents/CfgGroups.hpp, addons/insurgents/CfgVehicles.hpp, addons/insurgents/stringtable.xml
=> Fix common isUnconcious, Insurgents cleanup

addons/ai_disembark/XEH_preInit.sqf, addons/ai_disembark/initSettings.sqf, addons/ai_disembark/stringtable.xml
=> Add AI staying in immobilized vehicle chance

addons/tasks/functions/fnc_handleOnShow.sqf
=> Fix tasks onShow _taskConfigName undefined error

addons/tasks/functions/fnc_readDestination.sqf
=> Add support for 2D positions in tasks framework

addons/tasks/XEH_postInit.sqf, addons/tasks/XEH_preInit.sqf, addons/tasks/functions/fnc_createTask.sqf, addons/tasks/functions/fnc_readDestination.sqf
=> Fix marker and object not working as task destination

addons/difficulty/CfgAILevelPresets.hpp
=> Increase AI Precision to 0.3

addons/tanks/$PBOPREFIX$, addons/tanks/CfgEventHandlers.hpp, addons/tanks/README.md, addons/tanks/XEH_PREP.hpp, addons/tanks/XEH_preInit.sqf, addons/tanks/XEH_preStart.sqf, addons/tanks/config.cpp, addons/tanks/functions/fnc_canHeat.sqf, addons/tanks/functions/script_component.hpp, addons/tanks/script_component.hpp
=> Add tank thermal heating when used by AI

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Remove OldMan spotlight from main menu

addons/curator/XEH_postInit.sqf, addons/curator/XEH_preInit.sqf, addons/curator/functions/fnc_createCuratorModule.sqf
- use single group for all scripted curators
- move curator assign and unassign events to preInit
=> Scripted curator updates

addons/insurgents/README.md
=> Add example Insurgents gear mission config

addons/common/XEH_preInit.sqf, addons/pointing/$PBOPREFIX$, addons/pointing/CfgEventHandlers.hpp, addons/pointing/README.md, addons/pointing/XEH_PREP.hpp, addons/pointing/XEH_postInit.sqf, addons/pointing/XEH_preInit.sqf, addons/pointing/XEH_preStart.sqf, addons/pointing/config.cpp, addons/pointing/functions/fnc_keyPressVehicle.sqf, addons/pointing/functions/script_component.hpp, addons/pointing/initKeybinds.sqf, addons/pointing/initSettings.sqf, addons/pointing/script_component.hpp, addons/pointing/stringtable.xml
- Allow to send camera direction to current vehicle crew via DUI Squad Radar
=> Add pointing component

addons/back_to_game/functions/fnc_deletePlayerData.sqf, addons/back_to_game/functions/fnc_dialogConfirm.sqf, addons/back_to_game/functions/fnc_dialogReject.sqf, addons/back_to_game/functions/fnc_handleConnected.sqf, addons/back_to_game/functions/fnc_handleTeleport.sqf, addons/back_to_game/functions/fnc_savePlayerData.sqf, addons/back_to_game/functions/fnc_teleportPlayer.sqf
- title
- Add some INFO logging
- Add missing nil returns
Turned out to be problem with missionDisplay being unavailable. Simple WUAE `isNull(findDisplay 46)` fixed issue.
=> Fix back to game not working in 99.99% cases

addons/admin/$PBOPREFIX$, addons/admin/adminWhitelist.hpp, addons/admin/config.cpp, addons/admin/script_component.hpp
=> Add admins whitelist for debug console and CBA Settings

addons/main/DisplayEden.hpp, addons/main/stringtable.xml
=> Add wiki link to editor toolbar

addons/main_menu/CfgEventHandlers.hpp, addons/main_menu/XEH_multiplayerDisplay.sqf, addons/main_menu/script_component.hpp, addons/main_menu/stringtable.xml
- title
<details>
<summary>Images</summary>
</details>
Used spawns as CBA systems might be not initialized in main menu depending on world being loaded etc.
=> Add admin log in/out input in mission list and lobby

addons/main_menu/XEH_multiplayerDisplay.sqf
- title
- the buttons will just do nothing on local hosted, it's hard to detect it properly in mission screen ¯\_(ツ)_/¯
=> Remove local hosted check from admin login buttons

addons/friendly_fire/$PBOPREFIX$, addons/friendly_fire/CfgEventHandlers.hpp, addons/friendly_fire/README.md, addons/friendly_fire/XEH_postInit.sqf, addons/friendly_fire/XEH_preInit.sqf, addons/friendly_fire/config.cpp, addons/friendly_fire/initSettings.sqf, addons/friendly_fire/script_component.hpp, addons/friendly_fire/stringtable.xml
=> Add friendly fire incident logging

addons/tasks/README.md, addons/tasks/functions/fnc_handleShow.sqf
- Fix incorrect conditionEventsShow empty check
- Fix default values on conditionEvents*[] entries in example
=> Tasks fix default values on conditionEvents*[] entries in example

addons/curator/XEH_postInit.sqf, addons/curator/XEH_preInit.sqf
- Add delay for assign to prevent issues while unassign of old curator is still in progress
- Activate all addons for curator after assign
- Draw major map locations for curator
Closes #90
=> Scripted Curator improvements

addons/acre_gestures/$PBOPREFIX$, addons/acre_gestures/CfgEventHandlers.hpp, addons/acre_gestures/CfgMoves.hpp, addons/acre_gestures/XEH_PREP.hpp, addons/acre_gestures/XEH_postInit.sqf, addons/acre_gestures/XEH_preInit.sqf, addons/acre_gestures/XEH_preStart.sqf, addons/acre_gestures/config.cpp, addons/acre_gestures/functions/fnc_stopGesture.sqf, addons/acre_gestures/functions/script_component.hpp, addons/acre_gestures/initSettings.sqf, addons/acre_gestures/script_component.hpp, addons/acre_gestures/stringtable.xml, addons/common/XEH_preInit.sqf
- title
- Simple radio gestures when players are using radio.
Thanks to our friends at https://github.com/fparma (@diwako) for providing us with the code.
Based on https://github.com/fparma/fparma-mods/pull/29
=> Add ACRE radio gestures

addons/acre/XEH_PREP.hpp, addons/acre/XEH_postInit.sqf, addons/acre/functions/fnc_acreModulesPresent.sqf
=> Disable ACRE module when mission setup modules are detected

addons/friendly_fire/XEH_postInit.sqf
=> Delay friendly fire logging handler until player is initialized

addons/main_menu/XEH_multiplayerDisplay.sqf, addons/main_menu/stringtable.xml
=> Add #missions button to MP lobby

addons/acre/XEH_preInit.sqf, addons/acre/initSettings.sqf, addons/acre/stringtable.xml, addons/common/XEH_preInit.sqf
=> Add ACE Arsenal category with ACRE radios

addons/tasks/functions/fnc_createTask.sqf
- Somehow I've let than one slip
=> Code quality improvement in tasks framework

addons/back_to_game/XEH_PREP.hpp, addons/back_to_game/XEH_preInit.sqf, addons/back_to_game/functions/fnc_addHandler.sqf, addons/back_to_game/functions/fnc_addSaveHandler.sqf, addons/back_to_game/functions/fnc_dialogConfirm.sqf, addons/back_to_game/functions/fnc_savePlayerData.sqf, addons/common/XEH_preInit.sqf
- title
- Scripted API to allow custom handling of saving and loading of additional player data in back to game
- Save ACE Hearing earplugs data with custom handler
Obsoletes #104 
Closes #101
=> Back to game custom save handlers

addons/acre/XEH_PREP.hpp, addons/acre/XEH_preInit.sqf, addons/acre/config.cpp, addons/acre/functions/fnc_copyLeaderRadioChildrenActions.sqf, addons/acre/functions/fnc_copyLeaderSingleRadioChildrenActions.sqf, addons/acre/functions/fnc_getRadioDisplayName.sqf, addons/acre/script_component.hpp, addons/acre/stringtable.xml, addons/common/XEH_preInit.sqf
- title
- Allows to copy leader radio settings if within 50m of him. Works only for radios with channels due to public ACRE API limitations.
=> ACRE leader radio copy

addons/back_to_game/XEH_PREP.hpp, addons/back_to_game/XEH_postInit.sqf, addons/back_to_game/functions/fnc_handleDisconnected.sqf, addons/back_to_game/functions/fnc_savePlayerData.sqf, addons/back_to_game/initSettings.sqf, addons/back_to_game/stringtable.xml
=> Remove dead body when alive player disconnects

addons/acre_gestures/stringtable.xml
=> Fix typo in acre_gestures

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Remove main menu spotlight added with 2.00

addons/loading/XEH_loadingDisplay.sqf
=> Fix main menu loading screen author shown on mission loading screen

addons/back_to_game/functions/fnc_savePlayerData.sqf
- title
- fixes issues with ACRE radios after player reconnects
=> Filter ACRE radios in back to game data saving

addons/fries/XEH_postInit.sqf
=> Fix ace fries duplication

addons/friendly_fire/XEH_postInit.sqf
- title
Suprisingly there's only one object config lookup in whole AF Mods. So no much optimization  ¯\_(ツ)_/¯
Closes #114
=> Use configOf

addons/tanks/XEH_preInit.sqf
- title
- improvement to current system
Closes #115
=> Incremental tank heating on shot

addons/back_to_game/functions/fnc_dialogConfirm.sqf
- title
I could not reproduce the issue on lightly loaded dedicated server so not 100% confident it fixes the issue, but it should.
=> Prevent radio duplication in back to game

addons/spectator/XEH_PREP.hpp, addons/spectator/functions/fnc_addPlayerStatePanel.sqf, addons/spectator/functions/fnc_onDisplayLoad.sqf, addons/spectator/functions/script_component.hpp, addons/spectator/script_component.hpp, addons/spectator/stringtable.xml
=> Add player life state to spectator display

addons/acre/XEH_postInit.sqf, addons/acre_gestures/XEH_postInit.sqf, addons/back_to_game/XEH_postInit.sqf, addons/common/XEH_PREP.hpp, addons/common/XEH_preInit.sqf, addons/common/functions/fnc_runAfterSettingsInit.sqf, addons/friendly_fire/XEH_postInit.sqf
=> Ensure postInits dependent on CBA settings run after settings init

hemtt.toml
- title
- version in mod.cpp is not set on Linux/in CI/Workshop right now
=> Add Set_version hemtt script on linux

.github/workflows/arma.yml, .github/workflows/release.yml, .gitignore, hemtt.toml, tools/Publish.ps1
- title
- Allows us to use binarize.exe for models
- changed hemtt project to 0.7.0 format
- included hemtt.exe into repo
=> Use hemtt on windows containers

addons/tasks/XEH_postInit.sqf, addons/tasks/XEH_preInit.sqf, addons/tasks/functions/fnc_createTask.sqf, addons/tasks/functions/fnc_readOwners.sqf
- Create tasks in config order, this prevents BI framework from complaining if children task is created before its parent
- Warning when task owner object is non existent
- Additional logging
=> Minor Tasks improvements

addons/back_to_game/config.cpp
- title
- Looks like I've forgotten to PR this one
=> Add missing requiredAddons in b2g

addons/main_menu/CfgEventHandlers.hpp
- title
- This one also got lost somewhere.
=> Fix main_menu using wrong not unique name in display XEH

addons/loading/XEH_loadingDisplay.sqf, addons/loading/gui.hpp
- title
- ensure horizontal scrollbar is never shown
=> Move loading screen author to upper right corner

addons/acre/XEH_PREP.hpp, addons/acre/XEH_preInit.sqf, addons/acre/functions/fnc_getAllRadios.sqf
- fix radios with ID not being added into custom category (will not work until https://github.com/acemod/ACE3/pull/8088 is merged)
- fix missing category label
Fixes #139
=> Radios Arsenal category improvements

addons/tasks/README.md, addons/tasks/functions/fnc_handleOnShow.sqf
- title
- Scripted owners overwrite normal owners
Closes #136
=> Add scripted owners support for tasks

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Remove AoW spotlights from main menu

addons/acre/functions/fnc_initChannelsNames.sqf, addons/back_to_game/functions/fnc_dialogConfirm.sqf, addons/insurgents/XEH_preInit.sqf, addons/insurgents/functions/fnc_randomizeGear.sqf, addons/spectator/XEH_postInit.sqf, addons/spectator/functions/fnc_reloadLocal.sqf, addons/tagging/XEH_postInit.sqf, addons/tasks/functions/fnc_readDestination.sqf
- title
- https://community.bistudio.com/wiki/isNotEqualTo
=> Utilize isNotEqualTo

addons/common/XEH_preInit.sqf, addons/common/functions/fnc_createPlayerMarker.sqf, addons/tagging/XEH_postInit.sqf
=> Use getPlayerID in player markers feature

addons/back_to_game/XEH_preInit.sqf, addons/back_to_game/functions/fnc_deletePlayerData.sqf, addons/back_to_game/functions/fnc_getPlayerData.sqf, addons/back_to_game/functions/fnc_savePlayerData.sqf, addons/insurgents/XEH_preInit.sqf, addons/insurgents/script_component.hpp, addons/tasks/XEH_preInit.sqf, addons/tasks/functions/fnc_finishTask.sqf, addons/tasks/functions/fnc_showTask.sqf
=> Use HashMaps instead of Namespaces

addons/acre/README.md, addons/acre/XEH_PREP.hpp, addons/acre/XEH_postInit.sqf, addons/acre/functions/fnc_adjustVoiceVolume.sqf, addons/acre/initSettings.sqf, addons/acre/script_component.hpp, addons/acre/stringtable.xml
=> Add ACRE setting to change initial direct speech volume

addons/respawn/functions/fnc_onPlayerRespawn.sqf
- title
BI broke something ¯\_(ツ)_/¯
=> Fix backpacks not restored properly on respawn

addons/tasks/README.md
=> Update link to tasks icons

extension/Cargo.lock, extension/Cargo.toml, extension/src/lib.rs, extension/src/missions.rs
=> Use mission timestamp as an id in attendance extension

addons/extension_attendance/XEH_postInit.sqf, extension/Cargo.lock, extension/Cargo.toml, extension/src/lib.rs, extension/src/missions.rs
- title
- fix logging on server/hc
=> Post attendance data to web API

addons/common/XEH_preInit.sqf, addons/towing/$PBOPREFIX$, addons/towing/CfgEventHandlers.hpp, addons/towing/README.md, addons/towing/XEH_postInit.sqf, addons/towing/XEH_preInit.sqf, addons/towing/config.cpp, addons/towing/initSettings.sqf, addons/towing/script_component.hpp, addons/towing/stringtable.xml
- Auto-add tow ropes to heavy-duty vehicles, optionally to cars
=> Auto add tow ropes to vehicles

addons/killtracker/functions/fnc_dumpStats.sqf
=> Fix killtracker total kills count

addons/fries/XEH_postInit.sqf
Mod tries to add FRIES to all objects matching class. This change checks whether object has configuration for it.
=> FRIES - Do not try to add to unsupported objects

addons/debug/$PBOPREFIX$, addons/debug/CfgEventHandlers.hpp, addons/debug/README.md, addons/debug/XEH_preInit.sqf, addons/debug/XEH_preStart.sqf, addons/debug/config.cpp, addons/debug/script_component.hpp
- title
Added debug for potential issue in ACE Medical where unit is not killed despite transitioning to `Dead` state.
The issue is described as "blood is not flowing" ("krew nie płynie, medical się zepsuł") as the units are looking alive (alive _unit == true) as they're not "vanilla killed" so players are trying to treat players in this "zombie state".
I'll use it to see if https://github.com/acemod/ACE3/pull/8803 might be worth merging.
=> Add debug component

addons/spectator/functions/fnc_start.sqf
=> Spectator - Fix players being invincible while in spectator mode

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Main Menu - Remove SOGPF 1.3 showcases

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Remove Western Sahara 1.1 showcases

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Remove Spearhead 1944 showcases

addons/faces/$PBOPREFIX$, addons/faces/CfgFaces.hpp, addons/faces/README.md, addons/faces/config.cpp, addons/faces/script_component.hpp
Very simple component to port.
=> Port faces component from legacy mod

addons/difficulty/CfgDifficultyPresets.hpp, addons/difficulty/stringtable.xml
=> Difficulty - Add preset with third person enabled

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Main Menu - Remove Reaction Forces spotlight

addons/main_menu/CfgMainMenuSpotlight.hpp
=> Main Menu - Remove Spotlights from SPE 1.1

.hemtt/project.toml
=> Tools - Simplify hemtt config with "extends"

addons/spectator/functions/fnc_canSpectate.sqf, addons/spectator/initSettings.inc.sqf, addons/spectator/stringtable.xml
- Allow player to opt-out of unconscious spectator
Fixes #217
=> Spectator - Allow opt-out of unconscious spectator

addons/common/functions/fnc_modal.sqf
- HEMTT added a lint for this, and so our test found this
=> Common - fix format arg

addons/compatibility/map_esseker/CfgWorlds.hpp, addons/compatibility/map_esseker/config.cpp, addons/compatibility/map_esseker/script_component.hpp
=> Compatiblity - Fix Essekeer grid
