addons/main/CfgEden.hpp
addons/main/CfgModuleCategories.hpp
addons/main/DisplayEden.hpp
addons/main/README.md
addons/main/config.cpp
addons/main/stringtable.xml

- Add 3DEN categories and menu strip entry to main component, for usage in other components
- readme to `main` component, could we have it in all components from now on?

Add 3DEN categories and menu strip entry to main component

---

addons/killtracker/$PBOPREFIX$
addons/killtracker/CfgEventHandlers.hpp
addons/killtracker/README.md
addons/killtracker/XEH_PREP.hpp
addons/killtracker/XEH_preInit.sqf
addons/killtracker/XEH_preStart.sqf
addons/killtracker/config.cpp
addons/killtracker/functions/fnc_dumpStats.sqf
addons/killtracker/functions/script_component.hpp
addons/killtracker/script_component.hpp

- title
- dump ACEX stats to RPT on game end
- soft dependency
- relies on killtracker being enabled, thus CfgDebriefing entry is required
Example output:
```
1:12:02 ------ [START_KILLTRACKER_STATS] ------
1:12:02 KILLED: *AI* - Competitor  - [FatalInjury:Death]
1:12:02 KILLED: *AI* - Competitor  - [FatalInjury:Death]
1:12:02 KILLED: *AI* - Competitor  - [FatalInjury:Death]
1:12:02 KILLED: *AI* - Competitor  - [FatalInjury:Death]
1:12:02 ------ [END_KILLTRACKER_STATS] ------
```

Add killtracker component

---

addons/common/XEH_PREP.hpp
addons/common/XEH_preInit.sqf
addons/common/functions/fnc_isUnconscious.sqf
addons/spectator/$PBOPREFIX$
addons/spectator/CfgEventHandlers.hpp
addons/spectator/XEH_PREP.hpp
addons/spectator/XEH_postInit.sqf
addons/spectator/XEH_preInit.sqf
addons/spectator/XEH_preStart.sqf
addons/spectator/config.cpp
addons/spectator/functions/fnc_canSpectate.sqf
addons/spectator/functions/fnc_disable.sqf
addons/spectator/functions/fnc_enable.sqf
addons/spectator/functions/fnc_reloadLocal.sqf
addons/spectator/functions/fnc_restart.sqf
addons/spectator/functions/fnc_start.sqf
addons/spectator/functions/fnc_stop.sqf
addons/spectator/functions/fnc_toggle.sqf
addons/spectator/functions/script_component.hpp
addons/spectator/initSettings.sqf
addons/spectator/script_component.hpp
addons/spectator/stringtable.xml

- Add spectator module
- Highly customizable (selectable sides, camera modes)
- Allows spectating for ACE unconscious units (if allowed in settings)
- Separate settings customization for unconscious spectator
- Supports changing settings on the fly (restores old camera position, direction and target)

Add spectator

---

addons/common/XEH_PREP.hpp
addons/common/XEH_preInit.sqf
addons/common/functions/fnc_createPlayerMarker.sqf

- title
This PR allows to create markers with such IDs that they are seen by game as owned by the player. Markers created by it will be faded out when viewing different channel than the one it was created on, also it will correctly show owner on hover over marker. 
However due to usage `createMarker` command the marker will be visible to everyone, not only the player side, group etc. 
To handle this properly it would need to use `createMarkerLocal` with correct remote execution, jip handling etc. current implementation is enough for PvE usage thus I think it can be merged and improved in future if more robust/advanced functionality is needed.

Add function to create player owned marker

---

addons/curator/XEH_postInit.sqf
addons/curator/config.cpp
addons/curator/stringtable.xml

- Adds button to debug console which allows to assign yourself an Zeus Module
- Unassign current Zeus when assigning new one, allows to reasign yourself a new module in case something broke (happens rarely that functionality is lost despite having module assigned)

Add Zeus button to debug console

---

addons/flags/$PBOPREFIX$
addons/flags/CfgEventHandlers.hpp
addons/flags/CfgVehicles.hpp
addons/flags/FlagsVanilla.hpp
addons/flags/XEH_postInit.sqf
addons/flags/XEH_preInit.sqf
addons/flags/XEH_preStart.sqf
addons/flags/config.cpp
addons/flags/functions/script_component.hpp
addons/flags/script_component.hpp

- title
Flags created this way are a bit different than those created using dedicated flag texture, look img 2 for comparison between Spain flag created from marker and USA flag available in vanilla.
<details>
<summary>Created flagpoles list</summary>
- Belgium
- Canada
- Croatia
- CzechRepublic
- Denmark
- France
- Georgia
- Germany
- Greece
- Hungary
- Iceland
- Italy
- Luxembourg
- Netherlands
- Norway
- Poland
- Portugal
- Russia
- Slovakia
- Slovenia
- Spain
</details>
<details>
<summary>Images</summary>
</details>

Create flagpoles objects for vanilla country flag markers

---

addons/acre/$PBOPREFIX$
addons/acre/CfgEventHandlers.hpp
addons/acre/README.md
addons/acre/XEH_PREP.hpp
addons/acre/XEH_postInit.sqf
addons/acre/XEH_preInit.sqf
addons/acre/XEH_preStart.sqf
addons/acre/config.cpp
addons/acre/functions/fnc_init.sqf
addons/acre/functions/script_component.hpp
addons/acre/initSettings.sqf
addons/acre/script_component.hpp
addons/acre/stringtable.xml
addons/common/XEH_preInit.sqf
addons/common/stringtable.xml

- Create ACRE component
- Add `EGVAR(common,acre)` for checking if `acre_main` is loaded
- Add `ELSTRING(common,Enabled)` and `ELSTRING(common,Enabled_Description)` for generic "Enable component" string.
- title
This way we don't need ACRE module in PvP missions.

Allow ACRE Babel and PerSideRadios setup from settings

---

addons/spectator/XEH_postInit.sqf

- title
It did work even if spectator module was be disabled.

Fix spectator not disabled on unconscious

---

addons/back_to_game/functions/fnc_dialogConfirm.sqf
addons/back_to_game/functions/fnc_savePlayerData.sqf
addons/back_to_game/functions/fnc_teleportPlayer.sqf

- title
Previously when player changed group, he could not be teleported back to his leader. After rejoining he was in his original group. Now this behaviour is fixed and when player confirms teleportation, he joins his old group if possible.

Save player's group when disconnected

---

addons/main_menu/XEH_multiplayerDisplay.sqf

- title
<details>
<summary>
Before
</summary>
</details>
<details>
<summary>
After
</summary>
</details>

Fix password control spacing on MP missions screen

---

addons/back_to_game/functions/fnc_handleDisconnected.sqf

- Fix potential bug (or more like unwanted behaviour) of saving player data even if he is dead, thus giving him ability to come back where he died after reconnection.

Prevent saving player data if he was dead when disconnected

---

addons/remotesensors/$PBOPREFIX$
addons/remotesensors/CfgEventHandlers.hpp
addons/remotesensors/XEH_preInit.sqf
addons/remotesensors/config.cpp
addons/remotesensors/initSettings.sqf
addons/remotesensors/script_component.hpp
addons/remotesensors/stringtable.xml

- title
- https://community.bistudio.com/wiki/disableRemoteSensors
According to talk I had with our friends at Ark and @FPArma (@cyruz143 and @diwako) disabling this does not have any negative effects on gameplay. Only the 3 commands mentioned on wiki will be broken on clients but these are almost never used in standard gameplay scenarios.
Disabling this should net minimal fps gains when playing with standard non agent based AI.

Add setting to disable remote sensors on clients

---

addons/tasks/README.md

- title
No code changes included.
For solution read the `Using stringtable` chapter of tasks readme.
Closes #137.

Add information about stringtable usage in tasks framework

---

addons/spectator/functions/fnc_restart.sqf

- title
- prevents RPT spam at mission start

Prevent spectator restart if mission not started yet

---

addons/acre/XEH_postInit.sqf

- title
- ACRE sets the speaking volume after it syncs with TS. This can take some time and happen after we've changed the volume.

Fix ACRE speaking volume not applied on game start

---

addons/acre/XEH_postInit.sqf

- previous PR made it adjust after ACRE connects to TS, however, the volume adjustment is made in RPC call which can take a few ms, delaying it for a second should fix this for most of the cases.

Delay ACRE voice volume adjustment

---

addons/common/XEH_preInit.sqf
addons/safestart/README.md
addons/safestart/XEH_PREP.hpp
addons/safestart/XEH_postInitClient.sqf
addons/safestart/config.cpp
addons/safestart/functions/fnc_grenadeBindCondition.sqf
addons/safestart/functions/fnc_grenadeBindWarn.sqf
addons/safestart/functions/fnc_lowerWeapon.sqf
addons/safestart/functions/fnc_openKeybinding.sqf
addons/safestart/script_component.hpp
addons/safestart/stringtable.xml

- Add bind warning for player on mission start if he has grenade bound to `G`.
Ported from legacy AF Mods.

Port grenade bind warning from legacy AF Mods

---

addons/spectator/functions/fnc_onDisplayLoad.sqf

- title
- In today ~~gównozeus~~mission a lot of people had persisting blur in spectator after they died. Executing the added code fixed the issue.
See: https://github.com/acemod/ACE3/blob/master/addons/spectator/functions/fnc_ui.sqf#L35-L39

Spectator - Force remove death BIS_DeathBlur on spectator display load

---

addons/back_to_game/functions/fnc_savePlayerData.sqf

- title
In some care occurrences, there's something weird going with the loadouts and this causes an error in the ACRE filter loadout function:
```
21:38:27 Error in expression <nitLoadout _loadout;
};
if ((_loadout select 9) select 2 == "ItemRadioAcreFlag>
21:38:27   Error position: <select 9) select 2 == "ItemRadioAcreFlag>
21:38:27   Error Zero divisor
21:38:27 File idi\acre\addons\api\fnc_filterUnitLoadout.sqf..., line 27
```

Back to game - Add temporary debug

---

addons/killtracker/functions/fnc_dumpStats.sqf

- title
Used variable was not a public API so it got renamed in the merge of ACEX into ACE.

Fix killtracker for ACEX merged into ACE

---

addons/spectator/XEH_postInit.sqf

Spectator - Remove no longer necessary user input enable for ACE unconscious

---

addons/loading/XEH_loadingDisplay.sqf

- title
- Use fixed 256x256 pixels
Prevents issues on triple head:

Loading - Use absolute size for loading screen logo

---

addons/spotlight_block/$PBOPREFIX$
addons/spotlight_block/config.cpp
addons/spotlight_block/script_component.hpp

- title
- Tries to prevent from `delete CLASS` on main menu spotlight, won't work for more complex or scripted methods
- Works for FIR

Spotlight Block - Add component

---

.hemtt/project.toml
addons/compatibility/global_mobilization/CfgAmmo.hpp
addons/compatibility/global_mobilization/config.cpp
addons/compatibility/global_mobilization/script_component.hpp

- title
- It shoots at tanks now
- Might be bit stronger against light skinned vehicles

Compatibility - Add buff to Shilka API ammo

---

addons/spectator/functions/RscDisplayEGSpectator.sqf

- title
For some reason the DISPLAY macro is replaced with nothing by arma. Does not seem to be an issue in release as HEMTT does the preprocessing for sqfc. IDK why it seems to be fine for other macros in the file.
```
23:20:06 Error in expression <lElements = ["TreeGetAllElements"] call ;
private _groupElements = _allElements >
23:20:06   Error position: <;
private _groupElements = _allElements >
23:20:06   Error Invalid number in expression
23:20:06 File z\afm\addons\spectator\functions\RscDisplayEGSpectator.sqf..., line 92
```

Spectator - Do not use DISPLAY macro

---

.gitignore
.hemtt/launch.toml
.hemtt/missions/test.Stratis/cba_settings.sqf
.hemtt/missions/test.Stratis/description.ext
.hemtt/missions/test.Stratis/mission.sqm
.vscode/settings.json
addons/common/CfgVehicles.hpp
addons/common/config.cpp
addons/main/script_debug.hpp
addons/respawn/CfgVehicles.hpp
addons/respawn/README.md
addons/respawn/XEH_PREP.hpp
addons/respawn/XEH_postInit.sqf
addons/respawn/config.cpp
addons/respawn/functions/fnc_addZeusModules.sqf
addons/respawn/functions/fnc_moduleRespawn.sqf
addons/respawn/stringtable.xml

- 3DEN module that respawns all players from a side upon activation
- ZEN modules to respawn single player or whole sides

Respawn - Add 3DEN and Zeus modules
